// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kwbFq3AhS3bt8_hzG7Ngk1WDzA6uMGY',
    appId: '1:417969747335:web:bbf81921aa804d78e80f22',
    messagingSenderId: '417969747335',
    projectId: 'coworky-e91e1',
    authDomain: 'coworky-e91e1.firebaseapp.com',
    storageBucket: 'coworky-e91e1.appspot.com',
    measurementId: 'G-X0FSPPR4C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpgXWsWmFDC2ryRfQfNBEU3QkmuLCWKLg',
    appId: '1:417969747335:android:5a0807d9143c1581e80f22',
    messagingSenderId: '417969747335',
    projectId: 'coworky-e91e1',
    storageBucket: 'coworky-e91e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdX8ANtBMexT175R6UN4IYjO4_m47mZKA',
    appId: '1:417969747335:ios:8bd0adde1dc9fadce80f22',
    messagingSenderId: '417969747335',
    projectId: 'coworky-e91e1',
    storageBucket: 'coworky-e91e1.appspot.com',
    iosBundleId: 'com.example.coWorky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdX8ANtBMexT175R6UN4IYjO4_m47mZKA',
    appId: '1:417969747335:ios:8bd0adde1dc9fadce80f22',
    messagingSenderId: '417969747335',
    projectId: 'coworky-e91e1',
    storageBucket: 'coworky-e91e1.appspot.com',
    iosBundleId: 'com.example.coWorky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6kwbFq3AhS3bt8_hzG7Ngk1WDzA6uMGY',
    appId: '1:417969747335:web:89f0feaf704be936e80f22',
    messagingSenderId: '417969747335',
    projectId: 'coworky-e91e1',
    authDomain: 'coworky-e91e1.firebaseapp.com',
    storageBucket: 'coworky-e91e1.appspot.com',
    measurementId: 'G-CBJHSLD6XT',
  );
}
